namespace SalmonEgg.Presentation.Core.Mvux.ShellLayout;

public sealed record ShellLayoutSnapshot(
    NavigationPaneDisplayMode NavPaneDisplayMode,
    bool IsNavPaneOpen,
    double NavOpenPaneLength,
    double NavCompactPaneLength,
    bool SearchBoxVisible,
    double SearchBoxMinWidth,
    double SearchBoxMaxWidth,
    LayoutPadding TitleBarPadding,
    LayoutPadding NavViewPadding,
    double TitleBarHeight,
    bool CanShowSimultaneousAuxiliaryPanels,
    bool RightPanelVisible,
    double RightPanelWidth,
    double RightPanelOpenPaneLength,
    RightPanelMode RightPanelMode,
    bool BottomPanelVisible,
    double BottomPanelHeight,
    BottomPanelMode BottomPanelMode,
    bool IsNavResizerVisible,
    double LeftNavResizerLeft,
    bool CanToggleTaskOverviewPanel = true,
    bool CanToggleBottomPanel = true,
    bool ShowAuxiliaryTitleBarButtons = false,
    int TitleBarInteractiveRegionToken = 0,
    bool SupportsLocalTerminal = true);
