#!/usr/bin/env bash
# Renders a Homebrew formula for the SalmonEgg CLI from the checksums of the archives actually built by
# this release run.
#
# PATH ownership: `brew install` symlinks the binary into the Homebrew prefix's bin directory, which is
# already on PATH for any Homebrew user, and `brew uninstall` removes the symlink. The formula therefore
# never edits a shell profile.
#
# The SHA-256 values are read from the .sha256 sidecars produced by build-cli-artifacts.sh rather than
# recomputed here, so a formula can only ever describe archives that exist.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

ARTIFACT_DIR="$REPO_ROOT/artifacts/cli"
OUTPUT_PATH=""
VERSION=""
RELEASE_TAG=""
REPOSITORY="salmonloop/salmon-egg"

usage() {
  cat <<'USAGE'
Usage: build-cli-homebrew-formula.sh --version <version> [options]

Options:
  --version <version>     CLI display version (three-part numeric).
  --release-tag <tag>     Release tag the assets are attached to. Default: v<version>.
  --artifact-dir <dir>    Directory holding the archives and .sha256 sidecars. Default: artifacts/cli.
  --repository <owner/name>  GitHub repository. Default: salmonloop/salmon-egg.
  --output <path>         Formula output path. Default: <artifact-dir>/salmon-egg-cli.rb.
  -h, --help              Show this help.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --version) VERSION="${2:?--version requires a value}"; shift 2 ;;
    --version=*) VERSION="${1#*=}"; shift ;;
    --release-tag) RELEASE_TAG="${2:?--release-tag requires a value}"; shift 2 ;;
    --release-tag=*) RELEASE_TAG="${1#*=}"; shift ;;
    --artifact-dir) ARTIFACT_DIR="${2:?--artifact-dir requires a value}"; shift 2 ;;
    --artifact-dir=*) ARTIFACT_DIR="${1#*=}"; shift ;;
    --repository) REPOSITORY="${2:?--repository requires a value}"; shift 2 ;;
    --repository=*) REPOSITORY="${1#*=}"; shift ;;
    --output) OUTPUT_PATH="${2:?--output requires a value}"; shift 2 ;;
    --output=*) OUTPUT_PATH="${1#*=}"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [ -z "$VERSION" ]; then
  echo "--version is required." >&2
  usage >&2
  exit 2
fi

case "$VERSION" in
  [0-9]*.[0-9]*.[0-9]*) ;;
  *) echo "Version must be a three-part numeric version, got: '$VERSION'" >&2; exit 1 ;;
esac

RELEASE_TAG="${RELEASE_TAG:-v$VERSION}"
OUTPUT_PATH="${OUTPUT_PATH:-$ARTIFACT_DIR/salmon-egg-cli.rb}"

read_checksum() {
  local archive_name="$1"
  local sidecar="$ARTIFACT_DIR/$archive_name.sha256"
  if [ ! -f "$sidecar" ]; then
    echo "Checksum sidecar not found: $sidecar" >&2
    return 1
  fi

  local checksum
  checksum="$(awk '{print $1}' "$sidecar" | head -n 1)"
  if [ "${#checksum}" -ne 64 ]; then
    echo "Malformed SHA-256 in $sidecar: '$checksum'" >&2
    return 1
  fi

  printf '%s' "$checksum"
}

MAC_ARM_ARCHIVE="salmon-egg-cli-$VERSION-osx-arm64.tar.gz"
LINUX_X64_ARCHIVE="salmon-egg-cli-$VERSION-linux-x64.tar.gz"

MAC_ARM_SHA="$(read_checksum "$MAC_ARM_ARCHIVE")"
LINUX_X64_SHA="$(read_checksum "$LINUX_X64_ARCHIVE")"

BASE_URL="https://github.com/$REPOSITORY/releases/download/$RELEASE_TAG"

mkdir -p "$(dirname "$OUTPUT_PATH")"
cat > "$OUTPUT_PATH" <<FORMULA
# Generated by scripts/release/build-cli-homebrew-formula.sh. Do not edit by hand: the checksums below
# belong to the archives built by release $RELEASE_TAG.
class SalmonEggCli < Formula
  desc "Salmon Egg configuration management CLI"
  homepage "https://github.com/$REPOSITORY"
  version "$VERSION"
  license "MIT"

  on_macos do
    on_arm do
      url "$BASE_URL/$MAC_ARM_ARCHIVE"
      sha256 "$MAC_ARM_SHA"
    end
  end

  on_linux do
    on_intel do
      url "$BASE_URL/$LINUX_X64_ARCHIVE"
      sha256 "$LINUX_X64_SHA"
    end
  end

  def install
    # bin.install symlinks into the Homebrew prefix, which is already on PATH. No profile is edited.
    bin.install "salmon-egg"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/salmon-egg --version")
  end
end
FORMULA

echo "[cli-homebrew] formula: $OUTPUT_PATH"

if [ -n "${GITHUB_OUTPUT:-}" ]; then
  echo "formula-path=$OUTPUT_PATH" >> "$GITHUB_OUTPUT"
fi
