using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using SalmonEgg.Acp.Content;
using SalmonEgg.Acp.Mcp;
using SalmonEgg.Acp.Plan;
using SalmonEgg.Acp.Protocol;
using SalmonEgg.Acp.Tool;

namespace SalmonEgg.Acp.Serialization;

// Metadata-only generation, deliberately, not an oversight about performance.
//
// The default mode also emits a "fast path" SerializeHandler per type, and that handler resolves its
// nested contracts from the context instance rather than from the caller's JsonSerializerOptions -
// generated as JsonSerializer.Serialize(writer, value.ReplayFrom, SessionReplayFrom), where the
// property reads AcpJsonContext.Default.Options. So a nested converter invoked through the fast path
// sees the generated context's options, never the ones the caller passed.
//
// That matters here because the negotiated protocol version is carried on the options
// (AcpWireFormat). With the fast path on, serializing SessionResumeParams through the v2 contract
// reached SessionReplayFromJsonConverter with v1 options and threw "replayFrom is only available in
// protocolVersion 2" - the version silently did not survive one level of nesting. Metadata mode routes
// serialization through the metadata machinery, which resolves nested contracts from the options in
// force. AcpWireFormatTests asserts the mode by checking SerializeHandler is null, because the failure
// it prevents is invisible until a nested version-dependent converter happens to be exercised.
[JsonSourceGenerationOptions(
    GenerationMode = JsonSourceGenerationMode.Metadata,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    AllowOutOfOrderMetadataProperties = true)]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(InitializeParams))]
[JsonSerializable(typeof(InitializeResponse))]
[JsonSerializable(typeof(ClientInfo))]
[JsonSerializable(typeof(ClientCapabilities))]
[JsonSerializable(typeof(ClientSessionCapabilities))]
[JsonSerializable(typeof(SessionConfigOptionsCapabilities))]
[JsonSerializable(typeof(BooleanConfigOptionCapabilities))]
[JsonSerializable(typeof(FsCapability))]
[JsonSerializable(typeof(AgentInfo))]
[JsonSerializable(typeof(AgentCapabilities))]
[JsonSerializable(typeof(AgentAuthCapabilities))]
[JsonSerializable(typeof(LogoutCapabilities))]
[JsonSerializable(typeof(PromptCapabilities))]
[JsonSerializable(typeof(McpCapabilities))]
[JsonSerializable(typeof(SessionCapabilities))]
[JsonSerializable(typeof(SessionListCapabilities))]
[JsonSerializable(typeof(SessionResumeCapabilities))]
[JsonSerializable(typeof(SessionCloseCapabilities))]
[JsonSerializable(typeof(SessionDeleteCapabilities))]
[JsonSerializable(typeof(SessionAdditionalDirectoriesCapabilities))]
[JsonSerializable(typeof(AuthMethodDefinition))]
[JsonSerializable(typeof(List<AuthMethodDefinition>))]
[JsonSerializable(typeof(SessionNewParams))]
[JsonSerializable(typeof(SessionNewResponse))]
[JsonSerializable(typeof(SessionModesState))]
[JsonSerializable(typeof(SalmonEgg.Acp.Protocol.SessionMode))]
[JsonSerializable(typeof(SessionPromptParams))]
[JsonSerializable(typeof(SessionPromptResponse))]
[JsonSerializable(typeof(RequestPermissionSubject))]
[JsonSerializable(typeof(PlanUpdateContent))]
[JsonSerializable(typeof(PlanItemsUpdateContent))]
[JsonSerializable(typeof(V2PlanUpdate))]
[JsonSerializable(typeof(Icon))]
[JsonSerializable(typeof(TextCommandInput))]
[JsonSerializable(typeof(PromptImageCapabilities))]
[JsonSerializable(typeof(PromptAudioCapabilities))]
[JsonSerializable(typeof(PromptEmbeddedContextCapabilities))]
[JsonSerializable(typeof(McpHttpCapabilities))]
[JsonSerializable(typeof(TerminalAuthCapabilities))]
[JsonSerializable(typeof(ToolCallPermissionSubject))]
[JsonSerializable(typeof(CommandPermissionSubject))]
[JsonSerializable(typeof(SalmonEgg.Acp.Protocol.SessionWorkState))]
[JsonSerializable(typeof(StateSessionUpdate))]
[JsonSerializable(typeof(AgentWholeMessageUpdate))]
[JsonSerializable(typeof(UserWholeMessageUpdate))]
[JsonSerializable(typeof(AgentWholeThoughtUpdate))]
[JsonSerializable(typeof(TerminalSessionUpdate))]
[JsonSerializable(typeof(TerminalOutputChunkSessionUpdate))]
[JsonSerializable(typeof(TerminalOutput))]
[JsonSerializable(typeof(StructuredDiff))]
[JsonSerializable(typeof(ToolCallContentChunkUpdate))]
[JsonSerializable(typeof(DiffChange))]
[JsonSerializable(typeof(DiffPatch))]
[JsonSerializable(typeof(SessionLoadParams))]
[JsonSerializable(typeof(SessionLoadResponse))]
[JsonSerializable(typeof(SessionReplayFrom))]
[JsonSerializable(typeof(SessionResumeParams))]
[JsonSerializable(typeof(SessionResumeResponse))]
[JsonSerializable(typeof(SessionCloseParams))]
[JsonSerializable(typeof(SessionCloseResponse))]
[JsonSerializable(typeof(SessionDeleteParams))]
[JsonSerializable(typeof(SessionDeleteResponse))]
[JsonSerializable(typeof(SessionListParams))]
[JsonSerializable(typeof(SessionListResponse))]
[JsonSerializable(typeof(AgentSessionInfo))]
[JsonSerializable(typeof(SessionSetModeParams))]
[JsonSerializable(typeof(SessionSetModeResponse))]
[JsonSerializable(typeof(SessionSetConfigOptionParams))]
[JsonSerializable(typeof(SessionSetConfigOptionResponse))]
[JsonSerializable(typeof(SessionCancelParams))]
[JsonSerializable(typeof(CancelRequestParams))]
[JsonSerializable(typeof(AcpRequestId))]
[JsonSerializable(typeof(AuthenticateParams))]
[JsonSerializable(typeof(AuthenticateResponse))]
[JsonSerializable(typeof(LogoutParams))]
[JsonSerializable(typeof(LogoutResponse))]
[JsonSerializable(typeof(ElicitationCapabilities))]
[JsonSerializable(typeof(ElicitationFormCapabilities))]
[JsonSerializable(typeof(ElicitationUrlCapabilities))]
[JsonSerializable(typeof(ElicitationSchema))]
[JsonSerializable(typeof(ElicitationPropertySchema))]
[JsonSerializable(typeof(StringPropertySchema))]
[JsonSerializable(typeof(IntegerPropertySchema))]
[JsonSerializable(typeof(NumberPropertySchema))]
[JsonSerializable(typeof(BooleanPropertySchema))]
[JsonSerializable(typeof(MultiSelectPropertySchema))]
[JsonSerializable(typeof(CustomPropertySchema))]
[JsonSerializable(typeof(MultiSelectItems))]
[JsonSerializable(typeof(StringMultiSelectItems))]
[JsonSerializable(typeof(TitledMultiSelectItems))]
[JsonSerializable(typeof(CustomMultiSelectItems))]
[JsonSerializable(typeof(EnumOption))]
[JsonSerializable(typeof(StringFormat))]
[JsonSerializable(typeof(CreateElicitationRequest))]
[JsonSerializable(typeof(FormElicitationRequest))]
[JsonSerializable(typeof(UrlElicitationRequest))]
[JsonSerializable(typeof(CustomElicitationRequest))]
[JsonSerializable(typeof(CreateElicitationResponse))]
[JsonSerializable(typeof(ElicitationAcceptResponse))]
[JsonSerializable(typeof(ElicitationDeclineResponse))]
[JsonSerializable(typeof(ElicitationCancelResponse))]
[JsonSerializable(typeof(CustomElicitationResponse))]
[JsonSerializable(typeof(CompleteElicitationNotification))]
[JsonSerializable(typeof(List<EnumOption>))]
[JsonSerializable(typeof(Dictionary<string, ElicitationPropertySchema>))]
[JsonSerializable(typeof(AskUserRequest))]
[JsonSerializable(typeof(AskUserQuestion))]
[JsonSerializable(typeof(AskUserOption))]
[JsonSerializable(typeof(AskUserResponse))]
[JsonSerializable(typeof(PermissionOutcomeResult))]
[JsonSerializable(typeof(PermissionOption))]
[JsonSerializable(typeof(ReadTextFileResult))]
[JsonSerializable(typeof(SessionUpdateParams))]
[JsonSerializable(typeof(SessionUpdate))]
[JsonSerializable(typeof(ContentChunkUpdate))]
[JsonSerializable(typeof(AgentMessageUpdate))]
[JsonSerializable(typeof(UserMessageUpdate))]
[JsonSerializable(typeof(AgentThoughtUpdate))]
[JsonSerializable(typeof(ToolCallUpdate))]
[JsonSerializable(typeof(ToolCallStatusUpdate))]
[JsonSerializable(typeof(PlanUpdate))]
[JsonSerializable(typeof(CurrentModeUpdate))]
[JsonSerializable(typeof(ConfigOptionUpdate))]
[JsonSerializable(typeof(SessionInfoUpdate))]
[JsonSerializable(typeof(UsageUpdate))]
[JsonSerializable(typeof(UsageCost))]
[JsonSerializable(typeof(AvailableCommandsUpdate))]
[JsonSerializable(typeof(AvailableCommand))]
[JsonSerializable(typeof(AvailableCommandInput))]
[JsonSerializable(typeof(ConfigOption))]
[JsonSerializable(typeof(ConfigOptionValue))]
[JsonSerializable(typeof(ConfigOptionGroup))]
[JsonSerializable(typeof(TerminalCreateRequest))]
[JsonSerializable(typeof(TerminalCreateResponse))]
[JsonSerializable(typeof(TerminalOutputRequest))]
[JsonSerializable(typeof(TerminalOutputResponse))]
[JsonSerializable(typeof(TerminalExitStatus))]
[JsonSerializable(typeof(TerminalWaitForExitRequest))]
[JsonSerializable(typeof(TerminalWaitForExitResponse))]
[JsonSerializable(typeof(TerminalKillRequest))]
[JsonSerializable(typeof(TerminalKillResponse))]
[JsonSerializable(typeof(TerminalReleaseRequest))]
[JsonSerializable(typeof(TerminalReleaseResponse))]
[JsonSerializable(typeof(EnvVariable))]
[JsonSerializable(typeof(McpServer))]
[JsonSerializable(typeof(StdioMcpServer))]
[JsonSerializable(typeof(HttpMcpServer))]
[JsonSerializable(typeof(SseMcpServer))]
[JsonSerializable(typeof(CustomMcpServer))]
[JsonSerializable(typeof(McpHttpHeader))]
[JsonSerializable(typeof(McpEnvVariable))]
[JsonSerializable(typeof(ContentBlock))]
[JsonSerializable(typeof(TextContentBlock))]
[JsonSerializable(typeof(ImageContentBlock))]
[JsonSerializable(typeof(AudioContentBlock))]
[JsonSerializable(typeof(ResourceContentBlock))]
[JsonSerializable(typeof(ResourceLinkContentBlock))]
[JsonSerializable(typeof(Annotations))]
[JsonSerializable(typeof(EmbeddedResource))]
[JsonSerializable(typeof(ToolCallContent))]
[JsonSerializable(typeof(ContentToolCallContent))]
[JsonSerializable(typeof(DiffToolCallContent))]
[JsonSerializable(typeof(TerminalToolCallContent))]
[JsonSerializable(typeof(ToolCallLocation))]
[JsonSerializable(typeof(PlanEntry))]
[JsonSerializable(typeof(PlanEntryStatus))]
[JsonSerializable(typeof(PlanEntryPriority))]
[JsonSerializable(typeof(StopReason))]
[JsonSerializable(typeof(ToolCallKind))]
[JsonSerializable(typeof(ToolCallStatus))]
[JsonSerializable(typeof(Dictionary<string, object?>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(List<ContentBlock>))]
[JsonSerializable(typeof(List<ToolCallContent>))]
[JsonSerializable(typeof(IReadOnlyList<ToolCallContent>))]
[JsonSerializable(typeof(IReadOnlyList<ToolCallLocation>))]
[JsonSerializable(typeof(List<ToolCallLocation>))]
[JsonSerializable(typeof(List<SalmonEgg.Acp.Protocol.SessionMode>))]
[JsonSerializable(typeof(List<ConfigOption>))]
[JsonSerializable(typeof(List<McpServer>))]
[JsonSerializable(typeof(List<AskUserQuestion>))]
[JsonSerializable(typeof(List<PlanEntry>))]
public partial class AcpJsonContext : JsonSerializerContext
{
}
